sitemap:
  changefreq: weekly
module:
  mounts:
    - source: assets
      target: assets
    - source: layouts
      target: layouts
  imports:
    - path: github.com/mm-xyz/hugo-blox-builder-mod/modules/blox-core
